name: Branch and Commit Validation

on:
  pull_request:
    branches:
      - main

jobs:
  validate-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate branch name
        run: |
          BRANCH="${{ github.head_ref }}"

          echo "Branch: $BRANCH"

          # Validación de prefijos permitidos y descripción obligatoria
          if [[ ! "$BRANCH" =~ ^(feature|bugfix|hotfix|release|docs|chore)/.+$ ]]; then
            echo "❌ Branch name must start with a valid prefix followed by a description."
            echo "Allowed prefixes: feature/, bugfix/, hotfix/, release/, docs/, chore/"
            echo "Example: feature/add-event-catalog-card"
            exit 1
          fi

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install --save-dev @commitlint/cli @commitlint/config-conventional

      - name: Run commitlint
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose